#!/bin/bash
# 
# xmonad "startup hook" script. This gets run after xmonad is initialized,
# via the startupHook facility provided by xmonad. It's useful for 
# running any programs which you want to use within xmonad but
# which don't need to be initialized before xmonad is running. 
#
# Author: David Brewer
# Repository: https://github.com/davidbrewer/xmonad-ubuntu-conf

#
# TRAY ICON SOFTWARE
#

# Network manager, so we don't have to configure wifi at the command line.
if [ -z "$(pgrep nm-applet)" ] ; then
    nm-applet --sm-disable &
fi

# Applet for managing print jobs from the tray.
if [ -z "$(pgrep system-config-printer-applet)" ] ; then
    system-config-printer-applet &
fi

#
# APPLICATION LAUNCHER
#

# Use synapse as our app launcher. (-s: don't display until requested) 
if [ -z "$(pgrep gnome-do)" ] ; then
    gnome-do -s &
fi

##
# I now use envoy and pam to do this at login
#

# if [ -z "$(pgrep gpg-agent)" ] ; then
#     gpg-agent --enable-ssh-support --daemon > ~/.gpg-agent-init
#     source ~/.gpg-agent-init 
# fi

if [ -z "$(pgrep xscreensaver)" ] ; then
    xscreensaver &
fi

if [ -z "$(pgrep udiskie)" ] ; then
    udiskie --tray &
fi

if [ -z "$(pgrep scudcloud)" ] ; then
    scudcloud --minimized &
fi


# On login, we unlock the ssh keychain so we're not prompted for 
# passphrases later. We pipe /dev/null to ssh-add to make it realize 
# it's not running in a terminal. Otherwise, it won't launch the prompt.
# 
# If you don't use the ssh keychain you may not want this. Commented
# by default as it is assumed many users will not want this feature.

# export SSH_ASKPASS="/usr/bin/ssh-askpass"
# cat /dev/null | ssh-add &

